### ISSUE TITLE
Kodi 19 Matrix Support

### ISSUE THREAD

**Issue by OfficiallyMellow** [mpie/repo#2]
Hi, I am a long time user of your awesome DooFree addon, but since I switched to Kodi 19, the addon unfortunately does not work anymore due to the lack of Python 3 support.
Would you be so kind to release a Matrix version or is there a chance of this to happen anytime soon?

Sorry for my english and kind regards.

Keep up the great work!

**Comment by mpie** [comment]
Hi. Mellow,
Sorry for the late reply. I have looked into this issue and came to the conclusion that I can't update this addon for newer kodi versions without breaking changes to the older kodi versions. 
Therefore I will create a new DooFree version to support the latest kodi versions and drop support voor older kodi.

**Comment by OfficiallyMellow** [comment]
Hi mpie,
thank you so much for your response! That's great news!
I'll be patiently looking forward to the new version.

Kind Regards
Mellow

**Comment by mpie** [comment]
@OfficiallyMellow I have just created a new repo. Head over to https://github.com/mpie/doofree and download the repository.mpie-2.1.0.zip one

Have fun!

I will gradually update it when I have some more time, nut it should work from Kodi 18 (and higher but untested as I need some more time xD)

**Comment by OfficiallyMellow** [comment]
@mpie Thanks for the new repo! Unfortunately it's not working in Kodi 19. Log says:

Error Type: <class 'ModuleNotFoundError'>
Error Contents: No module named 'urlparse'
Traceback (most recent call last):
File "C:\Users\XXX\AppData\Roaming\Kodi\addons\plugin.video.doofree\default.py", line 3, in <module>
import urlparse, sys, xbmcaddon
ModuleNotFoundError: No module named 'urlparse'
-->End of Python script error report<--

**Comment by mpie** [comment]
Ha I see. I’ll rewrite the code this upcoming week so it will be fully Python3

**Comment by mpie** [comment]
@OfficiallyMellow good news!
I've managed to redo a bit of the code. It should now run on Kodi 19.

**Comment by OfficiallyMellow** [comment]
@mpie I can confirm it's working now. Thank you so much, you are awesome!

**Comment by mpie** [comment]
@OfficiallyMellow awesome!
